//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChat
    {
        public GroupChat()
        {
            this.GroupMessages = new HashSet<GroupMessages>();
        }
    
        public int groupChatId { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<int> orgInfoId { get; set; }
    
        public virtual OrgEvents OrgEvents { get; set; }
        public virtual OrgInfo OrgInfo { get; set; }
        public virtual ICollection<GroupMessages> GroupMessages { get; set; }
    }
}
