//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastRead
    {
        public int LastReadId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GroupChatId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
    }
}
