

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class TabangHubEntities : DbContext
{
    public TabangHubEntities()
        : base("name=TabangHubEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<OrgInfo> OrgInfoes { get; set; }

    public DbSet<OrgValidation> OrgValidations { get; set; }

    public DbSet<ProfilePicture> ProfilePictures { get; set; }

    public DbSet<Role> Roles { get; set; }

    public DbSet<UserAccount> UserAccounts { get; set; }

    public DbSet<UserRole> UserRoles { get; set; }

    public DbSet<VolunteerInfo> VolunteerInfoes { get; set; }

    public DbSet<vw_UserRoles> vw_UserRoles { get; set; }

    public DbSet<Skills> Skills { get; set; }

    public DbSet<VolunteerSkill> VolunteerSkill { get; set; }


    public virtual ObjectResult<sp_GetSkills_Result> sp_GetSkills(Nullable<int> userId)
    {

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("userId", userId) :
            new ObjectParameter("userId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSkills_Result>("sp_GetSkills", userIdParameter);
    }

}

}

