//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notificationId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> senderUserId { get; set; }
        public string type { get; set; }
        public string content { get; set; }
        public Nullable<int> broadcast { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> readAt { get; set; }
    }
}
