//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgAccount
    {
        public int orgId { get; set; }
        public string orgEmail { get; set; }
        public string orgPassword { get; set; }
        public Nullable<int> orgImageId { get; set; }
        public short status { get; set; }
        public int roleId { get; set; }
    
        public virtual OrgId OrgId1 { get; set; }
    }
}
