//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgEvent
    {
        public OrgEvent()
        {
            this.OrgEventImages = new HashSet<OrgEventImage>();
            this.OrgSkillRequirements = new HashSet<OrgSkillRequirement>();
        }
    
        public int eventId { get; set; }
        public Nullable<int> userId { get; set; }
        public string eventTitle { get; set; }
        public string eventDescription { get; set; }
        public Nullable<int> maxVolunteer { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<OrgEventImage> OrgEventImages { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<OrgSkillRequirement> OrgSkillRequirements { get; set; }
    }
}
