
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class OrgEvents
{

    public OrgEvents()
    {

        this.OrgEventImage = new HashSet<OrgEventImage>();

        this.OrgSkillRequirement = new HashSet<OrgSkillRequirement>();

        this.UserDonated = new HashSet<UserDonated>();

        this.Volunteers = new HashSet<Volunteers>();

    }


    public int eventId { get; set; }

    public Nullable<int> userId { get; set; }

    public string eventTitle { get; set; }

    public string eventDescription { get; set; }

    public Nullable<decimal> targetAmount { get; set; }

    public Nullable<int> maxVolunteer { get; set; }

    public Nullable<System.DateTime> dateStart { get; set; }

    public Nullable<System.DateTime> dateEnd { get; set; }

    public string location { get; set; }

    public string eventImage { get; set; }



    public virtual ICollection<OrgEventImage> OrgEventImage { get; set; }

    public virtual UserAccount UserAccount { get; set; }

    public virtual ICollection<OrgSkillRequirement> OrgSkillRequirement { get; set; }

    public virtual ICollection<UserDonated> UserDonated { get; set; }

    public virtual ICollection<Volunteers> Volunteers { get; set; }

}

}
