//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgId
    {
        public OrgId()
        {
            this.OrgAccount = new HashSet<OrgAccount>();
        }
    
        public int imageId { get; set; }
        public string idPicture1 { get; set; }
        public string idPicture2 { get; set; }
        public string idNumber { get; set; }
    
        public virtual ICollection<OrgAccount> OrgAccount { get; set; }
    }
}
