//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgValidation
    {
        public int orgValidationId { get; set; }
        public Nullable<int> userId { get; set; }
        public string idPicture1 { get; set; }
        public string idNumber1 { get; set; }
        public string idPicture2 { get; set; }
        public string idNumber2 { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
