
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class ProfilePicture
{

    public ProfilePicture()
    {

        this.OrgInfoes = new HashSet<OrgInfo>();

        this.VolunteerInfoes = new HashSet<VolunteerInfo>();

    }


    public int profileId { get; set; }

    public Nullable<int> userId { get; set; }

    public string profilePath { get; set; }



    public virtual ICollection<OrgInfo> OrgInfoes { get; set; }

    public virtual ICollection<VolunteerInfo> VolunteerInfoes { get; set; }

}

}
