
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class Role
{

<<<<<<< Updated upstream
    public Role()
    {

        this.UserRoles = new HashSet<UserRoles>();

    }


=======
>>>>>>> Stashed changes
    public int roleId { get; set; }

    public string roleName { get; set; }

<<<<<<< Updated upstream


    public virtual ICollection<UserRoles> UserRoles { get; set; }

=======
>>>>>>> Stashed changes
}

}
