//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public Skills()
        {
            this.OrgSkillRequirement = new HashSet<OrgSkillRequirement>();
            this.Rating = new HashSet<Rating>();
            this.VolunteerSkill = new HashSet<VolunteerSkill>();
            this.Volunteers = new HashSet<Volunteers>();
            this.VolunteerSkillsHistory = new HashSet<VolunteerSkillsHistory>();
        }
    
        public int skillId { get; set; }
        public string skillName { get; set; }
        public string skillImage { get; set; }
    
        public virtual ICollection<OrgSkillRequirement> OrgSkillRequirement { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual ICollection<VolunteerSkill> VolunteerSkill { get; set; }
        public virtual ICollection<Volunteers> Volunteers { get; set; }
        public virtual ICollection<VolunteerSkillsHistory> VolunteerSkillsHistory { get; set; }
    }
}
