//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.VolunteerSkills = new HashSet<VolunteerSkill>();
        }
    
        public int skillId { get; set; }
        public string skillName { get; set; }
        public string skillImage { get; set; }
    
        public virtual ICollection<VolunteerSkill> VolunteerSkills { get; set; }
    }
}
