//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.OrgEvents = new HashSet<OrgEvent>();
            this.OrgInfoes = new HashSet<OrgInfo>();
            this.OrgValidations = new HashSet<OrgValidation>();
            this.UserRoles = new HashSet<UserRole>();
            this.VolunteerInfoes = new HashSet<VolunteerInfo>();
        }
    
        public int userId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> userInfo { get; set; }
        public short status { get; set; }
        public int roleId { get; set; }
    
        public virtual ICollection<OrgEvent> OrgEvents { get; set; }
        public virtual ICollection<OrgInfo> OrgInfoes { get; set; }
        public virtual ICollection<OrgValidation> OrgValidations { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<VolunteerInfo> VolunteerInfoes { get; set; }
    }
}
