
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class UserAccount
{

    public UserAccount()
    {

        this.OrgEvents = new HashSet<OrgEvents>();

        this.OrgInfo = new HashSet<OrgInfo>();

        this.OrgValidation = new HashSet<OrgValidation>();

<<<<<<< Updated upstream
=======
        this.UserDonated = new HashSet<UserDonated>();

>>>>>>> Stashed changes
        this.UserRoles = new HashSet<UserRoles>();

        this.VolunteerInfo = new HashSet<VolunteerInfo>();

<<<<<<< Updated upstream
=======
        this.Volunteers = new HashSet<Volunteers>();

>>>>>>> Stashed changes
    }


    public int userId { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public Nullable<int> userInfo { get; set; }

    public short status { get; set; }

    public int roleId { get; set; }



    public virtual ICollection<OrgEvents> OrgEvents { get; set; }

    public virtual ICollection<OrgInfo> OrgInfo { get; set; }

    public virtual ICollection<OrgValidation> OrgValidation { get; set; }

<<<<<<< Updated upstream
=======
    public virtual ICollection<UserDonated> UserDonated { get; set; }

>>>>>>> Stashed changes
    public virtual ICollection<UserRoles> UserRoles { get; set; }

    public virtual ICollection<VolunteerInfo> VolunteerInfo { get; set; }

<<<<<<< Updated upstream
=======
    public virtual ICollection<Volunteers> Volunteers { get; set; }

>>>>>>> Stashed changes
}

}
