//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListOfEvent
    {
        public int Event_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Event_Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Total_Donation { get; set; }
        public Nullable<decimal> Target_Amount { get; set; }
        public Nullable<int> Total_Volunteer { get; set; }
        public Nullable<int> Maximum_Volunteer { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
