//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrganizationAccounts
    {
        public int User_Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public short Status { get; set; }
        public int Role_Id { get; set; }
        public string Org_Name { get; set; }
        public string Org_Type { get; set; }
        public string Description { get; set; }
        public string Contact_No { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Zip_Code { get; set; }
    }
}
