
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class vw_UserRoles
{

<<<<<<< Updated upstream
    public int UserRoles_ID { get; set; }

    public int userId { get; set; }
=======
    public int userRoleId { get; set; }
>>>>>>> Stashed changes

    public int roleId { get; set; }

    public string roleName { get; set; }

<<<<<<< Updated upstream
=======
    public int userId { get; set; }

>>>>>>> Stashed changes
    public string email { get; set; }

}

}
