//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VolunteerAccounts
    {
        public int User_Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> User_Info { get; set; }
        public short Status { get; set; }
        public int Role_Id { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public string Contact_No { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Zip_Code { get; set; }
        public Nullable<int> Profile { get; set; }
        public string Availability { get; set; }
        public string About_Me { get; set; }
    }
}
